---
- name: add haproxy repository key
  apt_key:
    url: "https://haproxy.debian.net/bernat.debian.org.gpg"
    state: present

- name: add haproxy repo
  apt_repository:
    repo: "deb http://httpredir.debian.org/debian jessie-backports main"
    filename: haproxy
    state: present
    update_cache: yes

- name: install haproxy
  apt:
    name: haproxy
    state: present
    default_release: jessie-backports

- name: Install certificates
  include_role:
    name:  letsencrypt

- name: merge the certificates into one
  shell: cd /etc/letsencrypt/live/{{ domain }} && cat fullchain.pem privkey.pem > {{ domain }}.pem

- name: configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
  notify: Restart haproxy
