---
- hosts: backend
  tasks:
    []

- hosts: haproxy
  user: root
  roles:
    - firewall
    - haproxy

- hosts: backend
  user: root
  roles:
    - ghost

- hosts: backend
  user: zozo
  roles:
    - ghost_install
