---
- hosts: haproxy
  gather_facts: true
  user: root
  roles:
    - firewall
    - haproxy

- hosts: backend
  gather_facts: true
  user: root
  roles:
    - ghost

- hosts: mysql
  user: root
  roles:
    - create_db

- hosts: backend
  user: zozo
  roles:
    - ghost_install
