apps:
#  - script    : "/usr/sbin/php-fpm7.0"
#    args      : "-c /etc/php/7.0/fpm/php.ini -y /etc/php/7.0/fpm/php-fpm.conf"
#    name      : 'php-fpm'
#    watch     : true
  - script    : "/usr/sbin/nginx"
    args      : "-c /etc/nginx/nginx.conf"
    name      : nginx
    watch     : false
