version: '3'
services:
  web:
    depends_on:
      - db
    image: zozo6015/startech-md:latest
    hostname: wp.startech-rd.tk
    ports:
      - "80:80"
    restart: always
    environment:
      MYSQL_HOST: db:3306
    volumes:
      - ./nginx/wp.startech-rd.tk.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./wp:/usr/share/nginx/html:rw

  db:
    image: percona:5.7
    hostname: db.startech-rd.tk
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: wp
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
