---
- name: install iptables-persistent
  apt:
    name: iptables-persistent
    state: present

- name: enable ip forward in sysctl.conf
  lineinfile:
    path: /etc/sysctl.conf
    line: "{{ item }}"
  with_items:
    - net.ipv4.ip_forward=1
    - net.ipv4.conf.all.forwarding=1
    - net.ipv4.conf.default.forwarding=1
    - net.ipv4.conf.eth0.forwarding=1
    - net.ipv4.conf.eth1.forwarding=1
    - net.ipv4.conf.lo.forwarding=1

- name: make sure ip forwarding is enabled using sysctl
  shell: sysctl -p

- name: load necesarry kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - ip_tables
    - ip_conntrack
    - ip_conntrack_irc
    - ip_conntrack_ftp

- name: enable masquerade for private range
  iptables:
    table: nat
    out_interface: eth0
    chain: POSTROUTING
    jump: MASQUERADE

- name: enable enabled and related traffic
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: enable ssh, http and https
  iptables:
    chain: INPUT
    ctstate: NEW
    protocol: tcp
    destination_port: "{{ item.port }}"
    jump: ACCEPT
    comment: "{{ item.comment }}"
  with_items:
    - { port: "22", comment: "ssh access" }
    - { port: "80", comment: "http access" }
    - { port: "443", comment: "https access" }

#- name: changing the input default rule to drop
#  iptables:
#    chain: INPUT
#    policy: DROP

- name: add portforward rules for the backend nodes
  iptables:
    table: nat
    chain: PREROUTING
    in_interface: eth0
    protocol: tcp
    destination_port: "{{ item.fw_port }}"
    jump: DNAT
    to_destination: "{{ item.ip }}:22"
  with_items:
    - { ip: '10.160.125.81', fw_port: '6015' }
    - { ip: '10.160.125.82', fw_port: '6016' }

- name: saving iptables rules
  shell: iptables-save > /etc/iptables/rules.v4
