---
- include_vars: secrets.yml

- name: Generate hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
  become: yes

- name: make sure ghost is not installed before running install
  file:
    name: /var/www/ghost
    state: absent
    owner: zozo
    group: zozo
    mode: 0755
  ignore_errors: true

- name: make sure ghost path exists
  file:
    name: /var/www/ghost
    state: directory
    owner: zozo
    group: zozo
    mode: 0755

- name: install ghost
  shell: cd /var/www/ghost && ghost install --url {{ url }} --ip 0.0.0.0 --db mysql --dbhost {{ mysql_db_host }} --dbuser {{ mysql_user }} --dbpass {{ mysql_pass }} --dbname {{ mysql_db }} --no-prompt --no-stack
  register: ghost
  ignore_errors: true

- debug: var=ghost

- name: start ghost service
  systemd:
    name: ghost_anytech-rd-tk
    state: started
    daemon_reload: yes
    enabled: true
  become: yes
