---
- include_vars: secrets.yml

- name: make sure ghost is not installed before running install
  shell: cd /var/www/ghost && ghost uninstall --force --no-prompt && rm -rf .ghost*

- name: install ghost
  shell: cd /var/www/ghost && ghost install local
  register: ghost

- name: copy config file
  template:
    src: config.production.json.j2
    dest: /var/www/ghost/config.production.json
    owner: zozo
    group: zozo

- name: removing development config file
  file:
    path: /var/www/ghost/config.development.json
    state: absent

- name: running database migration
  shell: cd /var/www/ghost/ && ghost setup migration

- name: create ghost systemd
  shell: cd /var/www/ghost/ && ghost setup systemd
